#!/usr/bin/env python3
import argparse
import hashlib
import hmac
import json
import os
import platform
import signal
import select
import subprocess
import sys
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
BT_FILE = SCRIPT_DIR / "collector.bt"
SCHEMA_VERSION = "xebpf-1.3.2"
ANON_VERSION = "hmac-sha256-v1"

def read_os_release():
    data = {}
    try:
        for line in Path("/etc/os-release").read_text(errors="replace").splitlines():
            if "=" in line:
                k, v = line.split("=", 1)
                data[k] = v.strip().strip('"')
    except Exception:
        pass
    return data

def get_bpftrace_version():
    try:
        p = subprocess.Popen(
            ["bpftrace", "--version"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            universal_newlines=True
        )
        stdout, stderr = p.communicate(timeout=10)
        text = (stdout or stderr or "").strip()
        if p.returncode == 0 and text:
            return text
    except Exception:
        pass
    return "unknown"

def load_key(path: Path):
    data = path.read_bytes().strip()
    if len(data) < 32:
        raise RuntimeError(f"Anonymization key {path} must contain at least 32 bytes")
    return data

def token(key, prefix, value, length=20):
    if value in (None, "", "-"):
        return None
    digest = hmac.new(key, str(value).encode("utf-8", "surrogatepass"), hashlib.sha256).hexdigest()
    return f"{prefix}_{digest[:length]}"

def uid_class(uid):
    try:
        u = int(uid)
        if u == 0:
            return "root"
        if 0 < u < 1000:
            return "system"
        return "user"
    except Exception:
        return "unknown"

def path_class(path):
    if not path or path == "-":
        return None
    mapping = [
        ("/etc/", "etc"), ("/var/", "var"), ("/tmp/", "tmp"),
        ("/home/", "home"), ("/root/", "root_home"), ("/usr/", "usr"),
        ("/opt/", "opt"), ("/srv/", "srv"), ("/proc/", "proc"),
        ("/sys/", "sys"), ("/dev/", "dev"), ("/run/", "run"),
    ]
    for prefix, cls in mapping:
        if path == prefix[:-1] or path.startswith(prefix):
            return cls
    if path.startswith("/"):
        return "other_absolute"
    return "relative"

def safe_id(value, field):
    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._-:")
    if not value or any(c not in allowed for c in value):
        raise ValueError(f"{field} contains unsupported characters")
    return value

def main():
    ap = argparse.ArgumentParser(description="Cross-environment eBPF research collector with source pseudonymization")
    ap.add_argument("--experiment-id", required=True)
    ap.add_argument("--workload-id", default="pilot")
    ap.add_argument("--label", choices=["benign", "malicious", "unknown"], default="unknown")
    ap.add_argument("--attack-id", default="none")
    ap.add_argument("--duration", type=int, default=60, help="Seconds; 0 means until Ctrl-C")
    ap.add_argument("--output-dir", default="/var/lib/ebpf-research")
    ap.add_argument("--hmac-key-path", required=True, help="Path to a user-generated HMAC-SHA256 key file (minimum 32 bytes)")
    ap.add_argument("--target-uid", type=int, default=None, help="Capture only events generated by this UID; omit for system-wide capture")
    args = ap.parse_args()

    for f in ("experiment_id", "workload_id", "attack_id"):
        setattr(args, f, safe_id(getattr(args, f), f.replace("_", "-")))

    if os.geteuid() != 0:
        raise SystemExit("ERROR: run as root")

    if not BT_FILE.exists():
        raise SystemExit(f"ERROR: missing {BT_FILE}")

    if not shutil_which("bpftrace"):
        raise SystemExit("ERROR: bpftrace is not installed. Run ./setup.sh first.")

    key = load_key(Path(args.hmac_key_path))
    osr = read_os_release()
    hostname = platform.node()
    host_id = token(key, "host", hostname)

    outroot = Path(args.output_dir)
    outroot.mkdir(parents=True, exist_ok=True)
    os.chmod(outroot, 0o700)

    stamp = time.strftime("%Y%m%d_%H%M%S")
    run_dir = outroot / f"{args.experiment_id}_{stamp}"
    run_dir.mkdir(mode=0o700)

    data_path = run_dir / "events.jsonl"
    metadata_path = run_dir / "metadata.json"
    stats_path = run_dir / "stats.json"

    metadata = {
        "schema_version": SCHEMA_VERSION,
        "anonymization": ANON_VERSION,
        "experiment_id": args.experiment_id,
        "workload_id": args.workload_id,
        "attack_id": args.attack_id,
        "label": args.label,
        "host_id": host_id,
        "os_id": osr.get("ID"),
        "os_version": osr.get("VERSION_ID"),
        "os_pretty_name": osr.get("PRETTY_NAME"),
        "kernel_release": platform.release(),
        "architecture": platform.machine(),
        "collector": "bpftrace-common-v1.3.2",
        "bpftrace_version": get_bpftrace_version(),
        "raw_identifiers_persisted": False,
        "capture_scope": "uid_scoped" if args.target_uid is not None else "system_wide",
        "target_uid_id": token(key, "uid", args.target_uid) if args.target_uid is not None else None,
        "target_uid_class": uid_class(args.target_uid) if args.target_uid is not None else None,
        "started_at_epoch": time.time(),
    }
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n")
    os.chmod(metadata_path, 0o600)

    bt_uid = args.target_uid if args.target_uid is not None else 4294967295
    cmd = ["bpftrace", "-q", str(BT_FILE), str(bt_uid)]
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        universal_newlines=True, bufsize=1
    )

    stop = False
    counts = {}
    malformed = 0

    def request_stop(signum=None, frame=None):
        nonlocal stop
        stop = True

    signal.signal(signal.SIGINT, request_stop)
    signal.signal(signal.SIGTERM, request_stop)

    deadline = None if args.duration == 0 else time.monotonic() + args.duration

    with data_path.open("w", buffering=1) as out:
        os.chmod(data_path, 0o600)
        try:
            while True:
                if deadline is not None and time.monotonic() >= deadline:
                    break
                if stop:
                    break

                # Do not block indefinitely waiting for an event. select() gives
                # the loop a bounded wait so duration/termination checks remain effective
                # even when the scoped UID is idle.
                wait_s = 0.20
                if deadline is not None:
                    wait_s = max(0.0, min(wait_s, deadline - time.monotonic()))
                readable, _, _ = select.select([proc.stdout], [], [], wait_s)
                if not readable:
                    if proc.poll() is not None:
                        break
                    continue

                line = proc.stdout.readline()
                if not line:
                    if proc.poll() is not None:
                        break
                    continue

                line = line.rstrip("\n")
                parts = line.split("\t", 5)
                if len(parts) != 6:
                    malformed += 1
                    continue

                event_type, ts_ns, pid, uid, comm, path = parts
                if event_type == "READY":
                    continue

                try:
                    ts_ns_i = int(ts_ns)
                    pid_i = int(pid)
                    uid_i = int(uid)
                except Exception:
                    malformed += 1
                    continue

                # Sensitive values exist only in this process memory.
                # Only pseudonyms/classes are persisted.
                event = {
                    "schema_version": SCHEMA_VERSION,
                    "event_type": event_type,
                    "timestamp_monotonic_ns": ts_ns_i,
                    "pid": pid_i,
                    "uid_id": token(key, "uid", uid_i),
                    "uid_class": uid_class(uid_i),
                    "process_id": token(key, "proc", comm),
                    "path_id": token(key, "path", path) if path != "-" else None,
                    "path_class": path_class(path),
                    "host_id": host_id,
                    "os_id": osr.get("ID"),
                    "os_version": osr.get("VERSION_ID"),
                    "kernel_release": platform.release(),
                    "experiment_id": args.experiment_id,
                    "workload_id": args.workload_id,
                    "attack_id": args.attack_id,
                    "label": args.label,
                    "anonymization": ANON_VERSION,
                }

                out.write(json.dumps(event, separators=(",", ":")) + "\n")
                counts[event_type] = counts.get(event_type, 0) + 1
        finally:
            try:
                proc.send_signal(signal.SIGINT)
                proc.wait(timeout=5)
            except Exception:
                proc.kill()
                proc.wait()

    stderr = proc.stderr.read() if proc.stderr else ""
    # Only collector diagnostics are persisted. bpftrace diagnostics should contain
    # no observed path/host/user data from this program.
    (run_dir / "collector_stderr.log").write_text(stderr)
    os.chmod(run_dir / "collector_stderr.log", 0o600)

    metadata["ended_at_epoch"] = time.time()
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n")

    stats = {
        "event_counts": counts,
        "total_events": sum(counts.values()),
        "malformed_lines": malformed,
        "exit_code": proc.returncode,
    }
    stats_path.write_text(json.dumps(stats, indent=2) + "\n")
    os.chmod(stats_path, 0o600)

    print(str(run_dir))
    print(json.dumps(stats, indent=2))

def shutil_which(name):
    for d in os.environ.get("PATH", "").split(os.pathsep):
        p = Path(d) / name
        if p.is_file() and os.access(p, os.X_OK):
            return str(p)
    return None

if __name__ == "__main__":
    main()
